version: '3.9'

services:
  postgres:
    image: postgres:17

    container_name: parking_postgres

    restart: always

    ports:
      - '5433:5432'

    environment:
      POSTGRES_DB: parking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
